package com.kingteller.bs.domain.customer;

public class CustomerPayJournal {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column customerpayjournal.id
     *
     * @ibatorgenerated Mon Apr 13 13:55:19 CST 2015
     */
    private Long id;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column customerpayjournal.paytool
     *
     * @ibatorgenerated Mon Apr 13 13:55:19 CST 2015
     */
    private String paytool;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column customerpayjournal.businessid
     *
     * @ibatorgenerated Mon Apr 13 13:55:19 CST 2015
     */
    private Long businessid;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column customerpayjournal.businessproductid
     *
     * @ibatorgenerated Mon Apr 13 13:55:19 CST 2015
     */
    private Long businessproductid;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column customerpayjournal.totalcash
     *
     * @ibatorgenerated Mon Apr 13 13:55:19 CST 2015
     */
    private Float totalcash;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column customerpayjournal.cointype
     *
     * @ibatorgenerated Mon Apr 13 13:55:19 CST 2015
     */
    private String cointype;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column customerpayjournal.customerorderdetailedid
     *
     * @ibatorgenerated Mon Apr 13 13:55:19 CST 2015
     */
    private Long customerorderdetailedid;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column customerpayjournal.paystatus
     *
     * @ibatorgenerated Mon Apr 13 13:55:19 CST 2015
     */
    private String paystatus;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column customerpayjournal.id
     *
     * @return the value of customerpayjournal.id
     *
     * @ibatorgenerated Mon Apr 13 13:55:19 CST 2015
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column customerpayjournal.id
     *
     * @param id the value for customerpayjournal.id
     *
     * @ibatorgenerated Mon Apr 13 13:55:19 CST 2015
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column customerpayjournal.paytool
     *
     * @return the value of customerpayjournal.paytool
     *
     * @ibatorgenerated Mon Apr 13 13:55:19 CST 2015
     */
    public String getPaytool() {
        return paytool;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column customerpayjournal.paytool
     *
     * @param paytool the value for customerpayjournal.paytool
     *
     * @ibatorgenerated Mon Apr 13 13:55:19 CST 2015
     */
    public void setPaytool(String paytool) {
        this.paytool = paytool;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column customerpayjournal.businessid
     *
     * @return the value of customerpayjournal.businessid
     *
     * @ibatorgenerated Mon Apr 13 13:55:19 CST 2015
     */
    public Long getBusinessid() {
        return businessid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column customerpayjournal.businessid
     *
     * @param businessid the value for customerpayjournal.businessid
     *
     * @ibatorgenerated Mon Apr 13 13:55:19 CST 2015
     */
    public void setBusinessid(Long businessid) {
        this.businessid = businessid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column customerpayjournal.businessproductid
     *
     * @return the value of customerpayjournal.businessproductid
     *
     * @ibatorgenerated Mon Apr 13 13:55:19 CST 2015
     */
    public Long getBusinessproductid() {
        return businessproductid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column customerpayjournal.businessproductid
     *
     * @param businessproductid the value for customerpayjournal.businessproductid
     *
     * @ibatorgenerated Mon Apr 13 13:55:19 CST 2015
     */
    public void setBusinessproductid(Long businessproductid) {
        this.businessproductid = businessproductid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column customerpayjournal.totalcash
     *
     * @return the value of customerpayjournal.totalcash
     *
     * @ibatorgenerated Mon Apr 13 13:55:19 CST 2015
     */
    public Float getTotalcash() {
        return totalcash;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column customerpayjournal.totalcash
     *
     * @param totalcash the value for customerpayjournal.totalcash
     *
     * @ibatorgenerated Mon Apr 13 13:55:19 CST 2015
     */
    public void setTotalcash(Float totalcash) {
        this.totalcash = totalcash;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column customerpayjournal.cointype
     *
     * @return the value of customerpayjournal.cointype
     *
     * @ibatorgenerated Mon Apr 13 13:55:19 CST 2015
     */
    public String getCointype() {
        return cointype;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column customerpayjournal.cointype
     *
     * @param cointype the value for customerpayjournal.cointype
     *
     * @ibatorgenerated Mon Apr 13 13:55:19 CST 2015
     */
    public void setCointype(String cointype) {
        this.cointype = cointype;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column customerpayjournal.customerorderdetailedid
     *
     * @return the value of customerpayjournal.customerorderdetailedid
     *
     * @ibatorgenerated Mon Apr 13 13:55:19 CST 2015
     */
    public Long getCustomerorderdetailedid() {
        return customerorderdetailedid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column customerpayjournal.customerorderdetailedid
     *
     * @param customerorderdetailedid the value for customerpayjournal.customerorderdetailedid
     *
     * @ibatorgenerated Mon Apr 13 13:55:19 CST 2015
     */
    public void setCustomerorderdetailedid(Long customerorderdetailedid) {
        this.customerorderdetailedid = customerorderdetailedid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column customerpayjournal.paystatus
     *
     * @return the value of customerpayjournal.paystatus
     *
     * @ibatorgenerated Mon Apr 13 13:55:19 CST 2015
     */
    public String getPaystatus() {
        return paystatus;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column customerpayjournal.paystatus
     *
     * @param paystatus the value for customerpayjournal.paystatus
     *
     * @ibatorgenerated Mon Apr 13 13:55:19 CST 2015
     */
    public void setPaystatus(String paystatus) {
        this.paystatus = paystatus;
    }
}