package com.kingteller.bs.domain.business;

import java.util.Date;

public class BusinessAudit {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column businessaudit.id
     *
     * @ibatorgenerated Mon Apr 13 13:55:19 CST 2015
     */
    private Long id;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column businessaudit.name
     *
     * @ibatorgenerated Mon Apr 13 13:55:19 CST 2015
     */
    private String name;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column businessaudit.comment
     *
     * @ibatorgenerated Mon Apr 13 13:55:19 CST 2015
     */
    private String comment;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column businessaudit.status
     *
     * @ibatorgenerated Mon Apr 13 13:55:19 CST 2015
     */
    private String status;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column businessaudit.updatetime
     *
     * @ibatorgenerated Mon Apr 13 13:55:19 CST 2015
     */
    private Date updatetime;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column businessaudit.aduitstatus
     *
     * @ibatorgenerated Mon Apr 13 13:55:19 CST 2015
     */
    private String aduitstatus;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column businessaudit.aduitstarttime
     *
     * @ibatorgenerated Mon Apr 13 13:55:19 CST 2015
     */
    private Date aduitstarttime;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column businessaudit.aduitovertime
     *
     * @ibatorgenerated Mon Apr 13 13:55:19 CST 2015
     */
    private Date aduitovertime;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column businessaudit.id
     *
     * @return the value of businessaudit.id
     *
     * @ibatorgenerated Mon Apr 13 13:55:19 CST 2015
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column businessaudit.id
     *
     * @param id the value for businessaudit.id
     *
     * @ibatorgenerated Mon Apr 13 13:55:19 CST 2015
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column businessaudit.name
     *
     * @return the value of businessaudit.name
     *
     * @ibatorgenerated Mon Apr 13 13:55:19 CST 2015
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column businessaudit.name
     *
     * @param name the value for businessaudit.name
     *
     * @ibatorgenerated Mon Apr 13 13:55:19 CST 2015
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column businessaudit.comment
     *
     * @return the value of businessaudit.comment
     *
     * @ibatorgenerated Mon Apr 13 13:55:19 CST 2015
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column businessaudit.comment
     *
     * @param comment the value for businessaudit.comment
     *
     * @ibatorgenerated Mon Apr 13 13:55:19 CST 2015
     */
    public void setComment(String comment) {
        this.comment = comment;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column businessaudit.status
     *
     * @return the value of businessaudit.status
     *
     * @ibatorgenerated Mon Apr 13 13:55:19 CST 2015
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column businessaudit.status
     *
     * @param status the value for businessaudit.status
     *
     * @ibatorgenerated Mon Apr 13 13:55:19 CST 2015
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column businessaudit.updatetime
     *
     * @return the value of businessaudit.updatetime
     *
     * @ibatorgenerated Mon Apr 13 13:55:19 CST 2015
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column businessaudit.updatetime
     *
     * @param updatetime the value for businessaudit.updatetime
     *
     * @ibatorgenerated Mon Apr 13 13:55:19 CST 2015
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column businessaudit.aduitstatus
     *
     * @return the value of businessaudit.aduitstatus
     *
     * @ibatorgenerated Mon Apr 13 13:55:19 CST 2015
     */
    public String getAduitstatus() {
        return aduitstatus;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column businessaudit.aduitstatus
     *
     * @param aduitstatus the value for businessaudit.aduitstatus
     *
     * @ibatorgenerated Mon Apr 13 13:55:19 CST 2015
     */
    public void setAduitstatus(String aduitstatus) {
        this.aduitstatus = aduitstatus;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column businessaudit.aduitstarttime
     *
     * @return the value of businessaudit.aduitstarttime
     *
     * @ibatorgenerated Mon Apr 13 13:55:19 CST 2015
     */
    public Date getAduitstarttime() {
        return aduitstarttime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column businessaudit.aduitstarttime
     *
     * @param aduitstarttime the value for businessaudit.aduitstarttime
     *
     * @ibatorgenerated Mon Apr 13 13:55:19 CST 2015
     */
    public void setAduitstarttime(Date aduitstarttime) {
        this.aduitstarttime = aduitstarttime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column businessaudit.aduitovertime
     *
     * @return the value of businessaudit.aduitovertime
     *
     * @ibatorgenerated Mon Apr 13 13:55:19 CST 2015
     */
    public Date getAduitovertime() {
        return aduitovertime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column businessaudit.aduitovertime
     *
     * @param aduitovertime the value for businessaudit.aduitovertime
     *
     * @ibatorgenerated Mon Apr 13 13:55:19 CST 2015
     */
    public void setAduitovertime(Date aduitovertime) {
        this.aduitovertime = aduitovertime;
    }
}