package com.kingteller.bs.domain.business;

import java.util.Date;

import com.fasterxml.jackson.databind.annotation.JsonSerialize;

@JsonSerialize(include=JsonSerialize.Inclusion.NON_NULL)
public class BusinessProductOffsale {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column businessproductoffsale.id
     *
     * @ibatorgenerated Mon Apr 13 13:55:19 CST 2015
     */
    private Long id;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column businessproductoffsale.businessproductid
     *
     * @ibatorgenerated Mon Apr 13 13:55:19 CST 2015
     */
    private Long businessproductid;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column businessproductoffsale.comment
     *
     * @ibatorgenerated Mon Apr 13 13:55:19 CST 2015
     */
    private String comment;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column businessproductoffsale.aduitstatus
     *
     * @ibatorgenerated Mon Apr 13 13:55:19 CST 2015
     */
    private String aduitstatus;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column businessproductoffsale.updatetime
     *
     * @ibatorgenerated Mon Apr 13 13:55:19 CST 2015
     */
    private Date updatetime;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column businessproductoffsale.bussinessid
     *
     * @ibatorgenerated Mon Apr 13 13:55:19 CST 2015
     */
    private Date bussinessid;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column businessproductoffsale.status
     *
     * @ibatorgenerated Mon Apr 13 13:55:19 CST 2015
     */
    private String status;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column businessproductoffsale.id
     *
     * @return the value of businessproductoffsale.id
     *
     * @ibatorgenerated Mon Apr 13 13:55:19 CST 2015
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column businessproductoffsale.id
     *
     * @param id the value for businessproductoffsale.id
     *
     * @ibatorgenerated Mon Apr 13 13:55:19 CST 2015
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column businessproductoffsale.businessproductid
     *
     * @return the value of businessproductoffsale.businessproductid
     *
     * @ibatorgenerated Mon Apr 13 13:55:19 CST 2015
     */
    public Long getBusinessproductid() {
        return businessproductid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column businessproductoffsale.businessproductid
     *
     * @param businessproductid the value for businessproductoffsale.businessproductid
     *
     * @ibatorgenerated Mon Apr 13 13:55:19 CST 2015
     */
    public void setBusinessproductid(Long businessproductid) {
        this.businessproductid = businessproductid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column businessproductoffsale.comment
     *
     * @return the value of businessproductoffsale.comment
     *
     * @ibatorgenerated Mon Apr 13 13:55:19 CST 2015
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column businessproductoffsale.comment
     *
     * @param comment the value for businessproductoffsale.comment
     *
     * @ibatorgenerated Mon Apr 13 13:55:19 CST 2015
     */
    public void setComment(String comment) {
        this.comment = comment;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column businessproductoffsale.aduitstatus
     *
     * @return the value of businessproductoffsale.aduitstatus
     *
     * @ibatorgenerated Mon Apr 13 13:55:19 CST 2015
     */
    public String getAduitstatus() {
        return aduitstatus;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column businessproductoffsale.aduitstatus
     *
     * @param aduitstatus the value for businessproductoffsale.aduitstatus
     *
     * @ibatorgenerated Mon Apr 13 13:55:19 CST 2015
     */
    public void setAduitstatus(String aduitstatus) {
        this.aduitstatus = aduitstatus;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column businessproductoffsale.updatetime
     *
     * @return the value of businessproductoffsale.updatetime
     *
     * @ibatorgenerated Mon Apr 13 13:55:19 CST 2015
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column businessproductoffsale.updatetime
     *
     * @param updatetime the value for businessproductoffsale.updatetime
     *
     * @ibatorgenerated Mon Apr 13 13:55:19 CST 2015
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column businessproductoffsale.bussinessid
     *
     * @return the value of businessproductoffsale.bussinessid
     *
     * @ibatorgenerated Mon Apr 13 13:55:19 CST 2015
     */
    public Date getBussinessid() {
        return bussinessid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column businessproductoffsale.bussinessid
     *
     * @param bussinessid the value for businessproductoffsale.bussinessid
     *
     * @ibatorgenerated Mon Apr 13 13:55:19 CST 2015
     */
    public void setBussinessid(Date bussinessid) {
        this.bussinessid = bussinessid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column businessproductoffsale.status
     *
     * @return the value of businessproductoffsale.status
     *
     * @ibatorgenerated Mon Apr 13 13:55:19 CST 2015
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column businessproductoffsale.status
     *
     * @param status the value for businessproductoffsale.status
     *
     * @ibatorgenerated Mon Apr 13 13:55:19 CST 2015
     */
    public void setStatus(String status) {
        this.status = status;
    }
}