package com.kingteller.bs.domain.business;

import java.util.Date;

import com.fasterxml.jackson.databind.annotation.JsonSerialize;

@JsonSerialize(include=JsonSerialize.Inclusion.NON_NULL)
public class BusinessProductStock {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column businessproductstock.id
     *
     * @ibatorgenerated Mon Apr 13 13:55:19 CST 2015
     */
    private Long id;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column businessproductstock.productid
     *
     * @ibatorgenerated Mon Apr 13 13:55:19 CST 2015
     */
    private Long productid;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column businessproductstock.businessid
     *
     * @ibatorgenerated Mon Apr 13 13:55:19 CST 2015
     */
    private Long businessid;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column businessproductstock.businessproductid
     *
     * @ibatorgenerated Mon Apr 13 13:55:19 CST 2015
     */
    private Long businessproductid;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column businessproductstock.status
     *
     * @ibatorgenerated Mon Apr 13 13:55:19 CST 2015
     */
    private String status;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column businessproductstock.updatetime
     *
     * @ibatorgenerated Mon Apr 13 13:55:19 CST 2015
     */
    private Date updatetime;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column businessproductstock.name
     *
     * @ibatorgenerated Mon Apr 13 13:55:19 CST 2015
     */
    private String name;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column businessproductstock.numbers
     *
     * @ibatorgenerated Mon Apr 13 13:55:19 CST 2015
     */
    private Integer numbers;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column businessproductstock.id
     *
     * @return the value of businessproductstock.id
     *
     * @ibatorgenerated Mon Apr 13 13:55:19 CST 2015
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column businessproductstock.id
     *
     * @param id the value for businessproductstock.id
     *
     * @ibatorgenerated Mon Apr 13 13:55:19 CST 2015
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column businessproductstock.productid
     *
     * @return the value of businessproductstock.productid
     *
     * @ibatorgenerated Mon Apr 13 13:55:19 CST 2015
     */
    public Long getProductid() {
        return productid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column businessproductstock.productid
     *
     * @param productid the value for businessproductstock.productid
     *
     * @ibatorgenerated Mon Apr 13 13:55:19 CST 2015
     */
    public void setProductid(Long productid) {
        this.productid = productid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column businessproductstock.businessid
     *
     * @return the value of businessproductstock.businessid
     *
     * @ibatorgenerated Mon Apr 13 13:55:19 CST 2015
     */
    public Long getBusinessid() {
        return businessid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column businessproductstock.businessid
     *
     * @param businessid the value for businessproductstock.businessid
     *
     * @ibatorgenerated Mon Apr 13 13:55:19 CST 2015
     */
    public void setBusinessid(Long businessid) {
        this.businessid = businessid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column businessproductstock.businessproductid
     *
     * @return the value of businessproductstock.businessproductid
     *
     * @ibatorgenerated Mon Apr 13 13:55:19 CST 2015
     */
    public Long getBusinessproductid() {
        return businessproductid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column businessproductstock.businessproductid
     *
     * @param businessproductid the value for businessproductstock.businessproductid
     *
     * @ibatorgenerated Mon Apr 13 13:55:19 CST 2015
     */
    public void setBusinessproductid(Long businessproductid) {
        this.businessproductid = businessproductid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column businessproductstock.status
     *
     * @return the value of businessproductstock.status
     *
     * @ibatorgenerated Mon Apr 13 13:55:19 CST 2015
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column businessproductstock.status
     *
     * @param status the value for businessproductstock.status
     *
     * @ibatorgenerated Mon Apr 13 13:55:19 CST 2015
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column businessproductstock.updatetime
     *
     * @return the value of businessproductstock.updatetime
     *
     * @ibatorgenerated Mon Apr 13 13:55:19 CST 2015
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column businessproductstock.updatetime
     *
     * @param updatetime the value for businessproductstock.updatetime
     *
     * @ibatorgenerated Mon Apr 13 13:55:19 CST 2015
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column businessproductstock.name
     *
     * @return the value of businessproductstock.name
     *
     * @ibatorgenerated Mon Apr 13 13:55:19 CST 2015
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column businessproductstock.name
     *
     * @param name the value for businessproductstock.name
     *
     * @ibatorgenerated Mon Apr 13 13:55:19 CST 2015
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column businessproductstock.numbers
     *
     * @return the value of businessproductstock.numbers
     *
     * @ibatorgenerated Mon Apr 13 13:55:19 CST 2015
     */
    public Integer getNumbers() {
        return numbers;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column businessproductstock.numbers
     *
     * @param numbers the value for businessproductstock.numbers
     *
     * @ibatorgenerated Mon Apr 13 13:55:19 CST 2015
     */
    public void setNumbers(Integer numbers) {
        this.numbers = numbers;
    }
}